-- MySQL Script generated by MySQL Workbench
-- Wed Jun 14 00:10:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema contractdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema contractdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `contractdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `contractdb` ;

-- -----------------------------------------------------
-- Table `contractdb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contractdb`.`role` (
  `rolename` VARCHAR(15) NOT NULL,
  `description` VARCHAR(255) NULL,
  `function` VARCHAR(255) NULL,
  `crttime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`rolename`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contractdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contractdb`.`user` (
  `username` VARCHAR(15) NOT NULL,
  `rolename` VARCHAR(15) NULL,
  `password` VARCHAR(20) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `crttime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`username`),
  INDEX `fk_user_role1_idx` (`rolename` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`rolename`)
    REFERENCES `contractdb`.`role` (`rolename`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contractdb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contractdb`.`customer` (
  `customername` VARCHAR(50) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `tel1` VARCHAR(20) NOT NULL,
  `tel2` VARCHAR(20) NULL,
  `email` VARCHAR(255) NOT NULL,
  `bank` VARCHAR(255) NULL,
  `account` VARCHAR(50) NULL,
  `remark` TEXT NULL,
  PRIMARY KEY (`customername`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contractdb`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contractdb`.`contract` (
  `contractId` VARCHAR(50) NOT NULL,
  `customername` VARCHAR(50) NOT NULL,
  `contractname` VARCHAR(255) NOT NULL,
  `beginTime` DATE NOT NULL,
  `endtime` DATE NOT NULL,
  `content` TEXT NOT NULL,
  `drafttime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`contractId`),
  INDEX `fk_contract_customer1_idx` (`customername` ASC),
  CONSTRAINT `fk_contract_customer1`
    FOREIGN KEY (`customername`)
    REFERENCES `contractdb`.`customer` (`customername`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contractdb`.`contract_process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contractdb`.`contract_process` (
  `contractId` VARCHAR(50) NOT NULL,
  `username` VARCHAR(15) NOT NULL,
  `type` ENUM('Countersign', 'Approve', 'Sign') NOT NULL,
  `state` ENUM('Unfinished', 'Completed', 'Rejected') NOT NULL,
  INDEX `fk_contract_process_user1_idx` (`username` ASC),
  INDEX `fk_contract_process_contract1_idx` (`contractId` ASC),
  CONSTRAINT `fk_contract_process_user1`
    FOREIGN KEY (`username`)
    REFERENCES `contractdb`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_process_contract1`
    FOREIGN KEY (`contractId`)
    REFERENCES `contractdb`.`contract` (`contractId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contractdb`.`contract_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contractdb`.`contract_state` (
  `contractId` VARCHAR(50) NOT NULL,
  `type` ENUM('Draft', 'Finalized', 'Countersigned', 'Approved', 'Signed') NOT NULL,
  `operationtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_contract_state_contract1_idx` (`contractId` ASC),
  CONSTRAINT `fk_contract_state_contract1`
    FOREIGN KEY (`contractId`)
    REFERENCES `contractdb`.`contract` (`contractId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
